# Generated by Django 4.0.2 on 2022-02-18 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('date', models.DateField(default=datetime.date(2022, 2, 18))),
            ],
        ),
    ]
